### ISSUE TITLE
Testing Environments and Corresponding Occupancy Grid

### ISSUE THREAD

**Issue by Siliconlad** [automat-ed/simulation#29]
The @automat-ed/autonomous team would like to have a set of small test environments for testing and quantitative analysis purposes. Some suggestions for test environments include:
1. Straight path
2. Curved path
3. Intersection (3-way and 4-way)
4. Circle

In addition, for each of these environments we need a [`nav_msgs/OccupancyGrid`](https://docs.ros.org/en/melodic/api/nav_msgs/html/msg/OccupancyGrid.html) that describes the free space of the environment. Essentially, it's a matrix where 0 means free space, 1 means occupied and -1 means unknown (or something along those lines, this will need to be double checked).

The construction of these Occupancy Grids, according to the navigation expert, can be done by taking a top down view of the environment and performing image thresholding based on the colour of the pathways. Some resources that could be useful include:
1. https://answers.opencv.org/question/186860/convert-image-to-occupancy-grid/
2. https://uk.mathworks.com/help/driving/ug/create-occupancy-grid-using-monocular-camera-sensor.html;jsessionid=e43a0cef6389d721f55ce3e14c03

Obviously larger environments will also be useful to test our software system more thoroughly. Creating occupancy grids for them may be more challenging. If doing them manually is not feasible, we may look at some sort of mapping algorithm, but I'm not too sure how well that would work considering the pathways are not bounded by any obstacles.

**Comment by Siliconlad** [comment]
Another useful resource may be the [`map_server` package](https://wiki.ros.org/map_server) for generating and serving the maps via ROS.

**Comment by SmejoTT** [comment]
@Siliconlad We need to either close this #29 or #3. #3 seems to match more what we need as an occupancy grid is done at the autonomous level. Although I can't see where the implementation is. Does it still need to be implemented?

**Comment by Siliconlad** [comment]
@SmejoTT I agree. I think we can close this and move the `OccupancyGrid` tasks to Autonomous.

**Comment by SmejoTT** [comment]
Closed. Test environments moved here #3 and occupancy grid moved here automat-ed/autonomous#14.
