### ISSUE TITLE
Add Lidar

### ISSUE THREAD

**Issue by enzo-inc** [automat-ed/simulation#9]
As part of the sensor integration for the robot, implement a Lidar and publish its readings to a ROS topic

- [ ] Choose appropriate model of Lidar
- [ ] Add Lidar to the robot model in simulation
- [ ] Publish LaserScan information from the lidar to a  ROS topic

**Comment by Siliconlad** [comment]
@enzo-inc I don't think we need to include the last task of subscribing to the topic on this issue because that'll happen in the Autonomous repo right?
